Autor:  
Manuel Eugenio Morocho Cayamcela, PhD

## Procesamiento y Transformación de Datos para Análisis de Crédito

### **Introducción:**

Esta lectura cubrirá el preprocesamiento y transformación de datos para el análisis de crédito. Utilizaremos un conjunto de datos de solicitudes de crédito con las siguientes columnas:

1. ID: Identificador único para cada registro.
2. Customer_ID: Identificador único para cada cliente.
3. Month: Mes en el que se registró la información.
4. Name: Nombre del cliente.
5. Age: Edad del cliente.
6. SSN: Número de Seguro Social del cliente.
7. Occupation: Ocupación del cliente.
8. Annual_Income: Ingreso anual del cliente.
9. Monthly_Inhand_Salary: Salario mensual disponible del cliente.
10. Num_Bank_Accounts: Número de cuentas bancarias del cliente.
11. Num_Credit_Card: Número de tarjetas de crédito del cliente.
12. Interest_Rate: Tasa de interés aplicada al cliente.
13. Num_of_Loan: Número de préstamos del cliente.
14. Type_of_Loan: Tipo de préstamo(s) del cliente.
15. Delay_from_due_date: Retraso desde la fecha de vencimiento del pago.
16. Num_of_Delayed_Payment: Número de pagos retrasados del cliente.
17. Changed_Credit_Limit: Límite de crédito modificado del cliente.
18. Num_Credit_Inquiries: Número de consultas de crédito realizadas por el cliente.
19. Credit_Mix: Mezcla de crédito del cliente.
20. Outstanding_Debt: Deuda pendiente del cliente.
21. Credit_Utilization_Ratio: Relación de utilización de crédito del cliente.
22. Credit_History_Age: Antigüedad del historial de crédito del cliente.
23. Payment_of_Min_Amount: Pago del monto mínimo realizado por el cliente.
24. Total_EMI_per_month: Total de cuotas mensuales del cliente.
25. Amount_invested_monthly: Cantidad invertida mensualmente por el cliente.
26. Payment_Behaviour: Comportamiento de pago del cliente.
27. Monthly_Balance: Saldo mensual del cliente.
28. Credit_Score: Puntuación de crédito del cliente.

### **Contenido:**

#### Importamos las librerías necesarias

In [46]:
import pandas as pd
import numpy as np

#### Carga de Datos

In [53]:
# Cargamos y mostramos los primeros registros de la base de datos credit_score.csv
data = pd.read_csv('/Users/eugenio/Documents/Notebooks_ArtificialIntelligence/Datasets/credit_score.csv')
data.head(10)

/var/folders/8j/f0xtldm91_1c2bpdr69fxgzw0000gn/T/ipykernel_83369/2464886221.py:2: DtypeWarning: Columns (26) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('/Users/eugenio/Documents/Notebooks_ArtificialIntelligence/Datasets/credit_score.csv')

,ID,Customer_ID,Month,Name,Age,SSN,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
0,0x1602,CUS_0xd40,January,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,...,_,809.98,26.822620,22 Years and 1 Months,No,49.574949,80.41529543900253,High_spent_Small_value_payments,312.49408867943663,Good
1,0x1603,CUS_0xd40,February,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,NaN,3,...,Good,809.98,31.944960,NaN,No,49.574949,118.28022162236736,Low_spent_Large_value_payments,284.62916249607184,Good
2,0x1604,CUS_0xd40,March,Aaron Maashoh,-500,821-00-0265,Scientist,19114.12,NaN,3,...,Good,809.98,28.609352,22 Years and 3 Months,No,49.574949,81.699521264648,Low_spent_Medium_value_payments,331.2098628537912,Good
3,0x1605,CUS_0xd40,April,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,NaN,3,...,Good,809.98,31.377862,22 Years and 4 Months,No,49.574949,199.4580743910713,Low_spent_Small_value_payments,223.45130972736786,Good
4,0x1606,CUS_0xd40,May,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,...,Good,809.98,24.797347,22 Years and 5 Months,No,49.574949,41.420153086217326,High_spent_Medium_value_payments,341.48923103222177,Good
5,0x1607,CUS_0xd40,June,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,NaN,3,...,Good,809.98,27.262259,22 Years and 6 Months,No,49.574949,62.430172331195294,!@9#%8,340.4792117872438,Good
6,0x1608,CUS_0xd40,July,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,...,Good,809.98,22.537593,22 Years and 7 Months,No,49.574949,178.3440674122349,Low_spent_Small_value_payments,244.5653167062043,Good
7,0x1609,CUS_0xd40,August,NaN,23,#F%$D@*&8,Scientist,19114.12,1824.843333,3,...,Good,809.98,23.933795,NaN,No,49.574949,24.785216509052056,High_spent_Medium_value_payments,358.12416760938714,Standard
8,0x160e,CUS_0x21b1,January,Rick Rothackerj,28_,004-07-5839,_______,34847.84,3037.986667,2,...,Good,605.03,24.464031,26 Years and 7 Months,No,18.816215,104.291825168246,Low_spent_Small_value_payments,470.69062692529184,Standard
9,0x160f,CUS_0x21b1,February,Rick Rothackerj,28,004-07-5839,Teacher,34847.84,3037.986667,2,...,Good,605.03,38.550848,26 Years and 8 Months,No,18.816215,40.39123782853101,High_spent_Large_value_payments,484.5912142650067,Good

#### Exploración de Tipos de Datos


Para entender qué tipo de datos tenemos, podemos usar el método `info()`.

In [48]:
# Mostramos la información de la base de datos 
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 28 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   ID                        100000 non-null  object
 1   Customer_ID               100000 non-null  object
 2   Month                     100000 non-null  object
 3   Name                      90015 non-null   object
 4   Age                       100000 non-null  object
 5   SSN                       100000 non-null  object
 6   Occupation                100000 non-null  object
 7   Annual_Income             100000 non-null  object
 8   Monthly_Inhand_Salary     84998 non-null   float64
 9   Num_Bank_Accounts         100000 non-null  int64
 10  Num_Credit_Card           100000 non-null  int64
 11  Interest_Rate             100000 non-null  int64
 12  Num_of_Loan               100000 non-null  object
 13  Type_of_Loan              88592 non-null   object
 14  Delay_from_due_date       100000 non-null  int64
 15  Num_of_Delayed_Payment    92998 non-null   object
 16  Changed_Credit_Limit      100000 non-null  object
 17  Num_Credit_Inquiries      98035 non-null   float64
 18  Credit_Mix                100000 non-null  object
 19  Outstanding_Debt          100000 non-null  object
 20  Credit_Utilization_Ratio  100000 non-null  float64
 21  Credit_History_Age        90970 non-null   object
 22  Payment_of_Min_Amount     100000 non-null  object
 23  Total_EMI_per_month       100000 non-null  float64
 24  Amount_invested_monthly   95521 non-null   object
 25  Payment_Behaviour         100000 non-null  object
 26  Monthly_Balance           98800 non-null   object
 27  Credit_Score              100000 non-null  object
dtypes: float64(4), int64(4), object(20)
memory usage: 21.4+ MB

**Observaciones:**
1. Hay valores faltantes presentes en el conjunto de datos.
2. El conjunto de datos tiene valores `object` y `float64`.

In [51]:
# Mostramos la cantidad de registros y columnas de la base de datos
data.describe(exclude=np.number).T

,count,unique,top,freq
ID,100000,100000,0x1602,1
Customer_ID,100000,12500,CUS_0xd40,8
Month,100000,8,January,12500
Name,90015,10139,Langep,44
Age,100000,1788,38,2833
SSN,100000,12501,#F%$D@*&8,5572
Occupation,100000,16,_______,7062
Annual_Income,100000,18940,36585.12,16
Num_of_Loan,100000,434,3,14386
Type_of_Loan,88592,6260,Not Specified,1408
Num_of_Delayed_Payment,92998,749,19,5327
Changed_Credit_Limit,100000,4384,_,2091
Credit_Mix,100000,4,Standard,36479
Outstanding_Debt,100000,13178,1360.45,24
Credit_History_Age,90970,404,15 Years and 11 Months,446
Payment_of_Min_Amount,100000,3,Yes,52326
Amount_invested_monthly,95521,91049,__10000__,4305
Payment_Behaviour,100000,7,Low_spent_Small_value_payments,25513
Monthly_Balance,98800,98792,__-333333333333333333333333333__,9
Credit_Score,100000,3,Standard,53174

**Observaciones:**

1. `Customer_ID` tiene 12500 valores únicos. Esto significa que tenemos datos de 12500 clientes.
2. `Month` solo tiene 8 valores únicos. Debemos analizar más a fondo qué meses están presentes.
3. `Age` tiene 1788 valores únicos. Esto parece extraño ya que el rango general de edad es de 0-100.
4. `SSN` tiene 12501 valores únicos, mientras que `Customer_ID` solo tiene 12500 valores únicos. Existe la posibilidad de que se haya ingresado un valor incorrecto de SSN para uno de los clientes, ya que la misma persona no puede tener múltiples SSN.

#### Identificación de Valores Faltantes

In [54]:
# Identificar valores faltantes
missing_values = data.isnull().sum()
missing_values

ID                              0
Customer_ID                     0
Month                           0
Name                         9985
Age                             0
SSN                             0
Occupation                      0
Annual_Income                   0
Monthly_Inhand_Salary       15002
Num_Bank_Accounts               0
Num_Credit_Card                 0
Interest_Rate                   0
Num_of_Loan                     0
Type_of_Loan                11408
Delay_from_due_date             0
Num_of_Delayed_Payment       7002
Changed_Credit_Limit            0
Num_Credit_Inquiries         1965
Credit_Mix                      0
Outstanding_Debt                0
Credit_Utilization_Ratio        0
Credit_History_Age           9030
Payment_of_Min_Amount           0
Total_EMI_per_month             0
Amount_invested_monthly      4479
Payment_Behaviour               0
Monthly_Balance              1200
Credit_Score                    0
dtype: int64

In [55]:
# Mostramos el porcentaje de valores faltantes
data.isnull().mean()*100

ID                           0.000
Customer_ID                  0.000
Month                        0.000
Name                         9.985
Age                          0.000
SSN                          0.000
Occupation                   0.000
Annual_Income                0.000
Monthly_Inhand_Salary       15.002
Num_Bank_Accounts            0.000
Num_Credit_Card              0.000
Interest_Rate                0.000
Num_of_Loan                  0.000
Type_of_Loan                11.408
Delay_from_due_date          0.000
Num_of_Delayed_Payment       7.002
Changed_Credit_Limit         0.000
Num_Credit_Inquiries         1.965
Credit_Mix                   0.000
Outstanding_Debt             0.000
Credit_Utilization_Ratio     0.000
Credit_History_Age           9.030
Payment_of_Min_Amount        0.000
Total_EMI_per_month          0.000
Amount_invested_monthly      4.479
Payment_Behaviour            0.000
Monthly_Balance              1.200
Credit_Score                 0.000
dtype: float64

#### Eliminación de columnas que no aportan información útil

La decisión de qué columnas eliminar depende en gran medida del contexto y del objetivo del análisis. Sin embargo, aquí hay algunas pautas generales que podemos considerar:

**Irrelevancia para el modelado**: Las columnas que contienen un valor único para cada fila (como un ID) generalmente no aportan información útil para un modelo de data mining y pueden ser eliminadas.

Vamos a usar la función `drop` de pandas para eliminar las columnas con valores únicos. 
`data.drop(...)`: Esta es la función de pandas que se utiliza para eliminar columnas o filas de un DataFrame.

Por ejemplo, la columna `'Name'` contiene los nombres de los individuos que han solicitado créditos. En general, los nombres de las personas no proporcionan información útil para un modelo de aprendizaje automático, ya que son únicos para cada individuo y no tienen una relación directa con otras variables.

Además, codificar columnas con valores únicos, podría resultar en un gran número de características únicas, lo que podría hacer el modelo sea más complejo y difícil de entrenar.

Por lo tanto, en la mayoría de los casos, es seguro eliminar la columna 'Name' del conjunto de datos. Sin embargo, hay excepciones. Por ejemplo, si los nombres tienen algún tipo de información codificada (como un prefijo que indica el género o el estatus social), podemos extraer esa información antes de eliminar la columna. Pero en la mayoría de los casos, especialmente si estás tratando con nombres reales de personas, es mejor eliminar la columna.

Las columnas `ID`, `SSN` y `Customer_ID` se eliminan generalmente por las siguientes razones:

**Irrelevancia para el modelado**: Estas columnas suelen ser identificadores únicos para cada registro o cliente. No contienen información útil para el modelado predictivo, ya que no tienen ninguna relación con las otras variables.

**Evitar el sobreajuste**: Si se incluyen en el modelo, pueden causar sobreajuste. El modelo podría aprender a hacer predicciones basándose en el ID del cliente, lo cual no es útil ni generalizable.

**Privacidad de los datos**: En algunos casos, los identificadores de los clientes se eliminan para proteger la privacidad de los clientes, especialmente cuando los datos se comparten o se publican.

In [56]:
# Eliminamos columnas que no aportan información relevante para el análisis
data = data.drop(['ID', 'SSN', 'Customer_ID', 'Name', 'Month'], axis=1) # Se elimina month ya que no aporta información relevante para el análisis
data.head()

,Age,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Type_of_Loan,Delay_from_due_date,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
0,23,Scientist,19114.12,1824.843333,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",3,...,_,809.98,26.822620,22 Years and 1 Months,No,49.574949,80.41529543900253,High_spent_Small_value_payments,312.49408867943663,Good
1,23,Scientist,19114.12,NaN,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",-1,...,Good,809.98,31.944960,NaN,No,49.574949,118.28022162236736,Low_spent_Large_value_payments,284.62916249607184,Good
2,-500,Scientist,19114.12,NaN,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",3,...,Good,809.98,28.609352,22 Years and 3 Months,No,49.574949,81.699521264648,Low_spent_Medium_value_payments,331.2098628537912,Good
3,23,Scientist,19114.12,NaN,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",5,...,Good,809.98,31.377862,22 Years and 4 Months,No,49.574949,199.4580743910713,Low_spent_Small_value_payments,223.45130972736786,Good
4,23,Scientist,19114.12,1824.843333,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",6,...,Good,809.98,24.797347,22 Years and 5 Months,No,49.574949,41.420153086217326,High_spent_Medium_value_payments,341.48923103222177,Good

#### Tratamiento de la columna `Age`

In [18]:
# Mostramos los valores únicos de la columna 'Age'
print(list(data['Age'].unique()))

['23', '-500', '28_', '28', '34', '54', '55', '21', '31', '33', '34_', '7580', '30', '30_', '24', '24_', '44', '45', '40', '41', '32', '33_', '35', '35_', '36', '39', '37', '181', '20', '46', '26', '42', '19', '31_', '48', '995', '40_', '37_', '38', '54_', '5079', '43', '21_', '22', '6409', '16', '7080', '18', '849', '3885', '20_', '15', '27', '43_', '38_', '25', '3052', '14', '5342', '17', '18_', '4431', '2657', '2111_', '46_', '47', '1032', '16_', '19_', '47_', '456', '5717', '53_', '53', '56', '25_', '27_', '55_', '3169', '1191', '29', '42_', '7140', '48_', '49', '49_', '8233', '6955', '2534', '3115', '7657', '51', '50', '5112', '50_', '32_', '6452', '2744', '22_', '17_', '1439', '29_', '5795', '4872', '1772', '15_', '1383', '5657', '52', '1934', '51_', '8352', '3734', '26_', '2056', '39_', '7508', '2339', '14_', '8406', '1424', '36_', '6953', '5626', '4471', '548', '44_', '769', '5490', '525', '4202', '3665', '7670_', '4670', '3616', '6922', '6619', '1808', '7992', '45_', '223', '1232', '4659', '6895', '395', '7099', '6048', '3936', '3512', '123', '5639', '471', '7359', '23_', '4049', '5053', '2109', '7183', '5604', '1206', '6835', '4067', '41_', '1812', '1170', '3625', '6354', '3724', '480', '5610', '4710', '4351', '52_', '5784', '3937', '3542', '2239', '5645', '7425', '7851', '2027', '6306', '835', '3513', '6846', '6868', '7805', '7274', '831', '8394', '2751', '733_', '783', '2455', '5612', '2402', '4119', '4645', '8105', '1400', '7431', '3666', '2350', '491', '1116', '692', '5429', '4745', '4017', '3279', '651', '5611', '5769_', '6586', '7699', '919', '6765', '5376', '2546', '112', '3909', '5054', '8655', '4383_', '2824', '56_', '7865', '2823', '6365', '5688', '6178', '886', '3353', '8562', '7750', '5186', '8080', '3553', '5537', '3967', '6520', '2650_', '1335', '2054', '7068', '6100', '2636', '1753', '6389', '2419', '2033', '2961', '3307_', '5504', '4060', '5237', '2297', '5583', '4958', '6395', '3319', '7705', '4820', '2456', '5194', '5154', '4155', '7336', '7195', '8005', '5165', '3861', '2584', '2563', '5592', '3771', '1188', '5017', '8034', '5256', '8173', '6962_', '3578', '4572', '5589_', '328', '1678', '1512', '6556_', '5430', '8442', '4517', '7525', '1203', '4260', '7980', '7153', '2400', '6331', '3715', '3285', '8043', '8250', '8628', '8608', '7016', '989', '359', '8155', '2090', '4126', '3791', '5782', '6292', '8662', '1681', '1338', '8000', '7935', '5608', '1006', '1451', '622', '4857', '2369', '8216', '7330', '7289', '3601', '4127', '236', '6707', '493', '4682', '287', '375', '5195', '1969', '5788', '6413', '2388', '5152', '3986', '1715', '8200', '4336', '8299', '1308', '3888', '1051', '134', '5897', '6350', '2379', '3197', '3341', '8674', '7123', '556', '1083', '1447_', '7032', '5579', '1692', '4204', '7968', '1148', '2980', '4626', '3492', '1323', '2799', '6426', '186', '5498', '7060', '1752', '1816', '609', '2514', '6276', '4365', '8421', '8153_', '4609', '1625', '2614', '4603', '7026', '4010', '624', '1143', '5870', '3607', '8505', '528', '1578', '4404', '4414', '6704', '2509', '7456', '7353', '3075', '2081', '925', '4021', '3602', '5930', '306', '7197', '1066', '4527', '6510', '1062', '5221', '7166', '4391', '6651', '1227', '7112', '3214', '8472', '836', '7553', '7504', '1357', '3284', '2721', '6385', '2997', '2451', '3480', '3357', '711', '8632', '1388', '5696', '5524', '356', '6608', '5705', '8567', '3132', '1433', '1695', '8639', '8582', '2275', '4959', '3834_', '623', '7295', '3345', '3493', '182', '126', '6744_', '4390', '7715', '6130', '6471_', '7723_', '3768', '4178', '4630', '1420', '6417', '2560', '3985', '3750', '4444', '234', '3795', '637', '6649', '4380', '5714', '7693', '2174', '2366', '5781', '5677', '3038', '4897', '7937', '365', '7640_', '6408_', '1112', '3546', '8424', '124', '3502_', '5747', '8082', '7564', '1436', '3519', '6175', '2091', '8249', '7316_', '2578', '4687', '4163', '5796', '5123', '6943', '8338', '6345', '1364', '6777', '4782', '5981', '963', '5907', '6978', '673', '6322', '6384', '3036', '1270', '8561', '634', '2352', '6800', '118', '1010', '2395', '6781', '5520', '7042', '8592', '1868', '4307', '2764', '6796', '6646', '142', '6141', '1852', '4416', '8466', '4576', '3410', '8151', '890', '3581', '6925', '5479', '1102_', '8669_', '5074', '2463_', '3940', '5508', '1788', '216', '5173', '7965', '7987', '6666_', '921', '4719', '7092', '1657', '5738', '349', '6995', '7441', '5976', '762', '6485', '7702', '5708', '946', '4564', '3093', '6767', '3933', '3458', '1300', '5851', '774', '2577', '1811', '7480', '7113', '6273', '7235', '1452', '4058', '7520', '7414', '4370', '1853', '4649', '7845', '2864', '7925', '5550', '4165', '6411', '4063', '3215', '169', '99', '3055_', '1248_', '586', '2386', '5649', '8520', '100', '3978', '3244', '3778', '879', '1024', '423', '3938', '2882', '6036', '6037', '1484', '4643', '4510', '3146', '8514', '2220_', '6360', '362', '5996', '6892', '2159_', '5001', '576', '5018', '387', '4890', '5507', '4661', '1386', '330', '6074', '6970', '102', '5906', '203', '3640', '8124', '4484', '2778', '2434', '742', '7794', '4177', '4246', '208', '5765', '7710', '1734', '5202', '853', '3450', '1630', '3843', '7038', '8384', '8179', '5551', '6593', '7490', '2574', '1644', '111', '4975', '5478', '1176', '1418', '4679', '5751', '3779', '6611', '325', '7879', '6227', '6111', '573', '3726', '6722', '4732', '1754', '3966', '2437', '2212', '8081', '4194', '3119', '7549', '4583_', '3452', '1908', '3988_', '5621', '7178', '5741', '4774', '5116', '3378', '8302', '7651', '404', '3023', '5032', '4787', '305', '4107', '381', '8623', '6407', '3675', '1265', '399', '2461', '2977', '3490', '438', '1328', '2037', '1609', '7325', '8682', '4470', '899', '5532', '4083', '3096', '1971', '1094', '1294', '7736', '6366', '5287', '4244', '3853', '4214', '1402', '2672', '5008', '2155_', '2756', '4846', '7773', '2182', '5994', '4980', '6301', '3363', '8663', '1520', '678', '4056', '7279', '828', '4076', '1491', '6697', '5340', '813', '6001', '5288', '6197', '5177', '7014', '1686', '2382', '1378', '2650', '3264', '6006', '4736', '4213', '532', '506', '3276', '4525', '6653', '8306', '5117', '2048', '3701', '95', '1387', '6799', '267', '1786', '7787', '7797', '4590', '6378', '3369', '4542', '1366', '540', '3899', '6770_', '1497', '7377', '6550', '5539', '7133', '5156', '5742', '1363', '1095', '1648', '1985', '4607', '993', '1330', '5066', '6463', '6349', '2988', '6691', '3145', '793', '1119', '8159', '8396', '3193', '3085', '6971', '5959', '1843_', '449', '5377', '4387', '5902', '620', '514', '252', '6915', '3642', '2974', '6381', '652', '1367_', '553', '1355', '4277', '7713', '8291', '8154', '7933', '2347', '6098', '2731', '3742_', '2593', '4232', '5909', '2171_', '4120', '2449', '4311', '8296', '7556', '1404', '7856', '640', '2847', '2093', '5109_', '1571', '846', '1435', '8333', '6863', '655', '6262', '4914', '1053', '3747', '4931', '7315', '292', '2499', '4847', '736', '2858', '6633', '7286', '2989', '4135', '3639', '4746', '1787', '4298', '8049', '2696', '6909', '7894', '8525', '1947', '7765', '8004', '8234', '6708', '2404', '6506', '1661', '8246', '7923', '2047', '3365', '4863', '701', '2184', '8450', '581', '502', '1618', '2077', '737', '8251', '2305', '7298', '221', '6663', '6657', '6588', '3463', '6337', '6516', '3984_', '2076', '2513', '6280', '3237', '3454', '4622', '5712', '275', '240', '5868', '568', '2096', '2170', '8235', '986', '5471', '1785', '1593', '2474_', '2933', '6731', '7131', '7444', '5046_', '4133', '3258', '4407', '7715_', '1565', '6159', '2276', '7459', '3891', '3205', '2117', '7806', '6638', '8271', '3920', '2843', '4881', '4909', '6283', '4948', '6894', '5041', '7619', '7063', '3952', '2486', '5936', '6581', '1384', '8260', '6286', '5111', '4923', '7694', '1220', '6841', '1540', '2181', '4946', '2822', '4494', '7912', '1956', '6427', '5924', '8386', '1642', '529', '4655', '8371', '4663', '5818', '2895', '8389', '3930', '1429', '6652', '3764', '8552', '4775', '5132', '2654', '2749', '7438', '3629', '5253', '2208', '2713', '885', '6425', '7690', '2329_', '6124', '2773', '293', '3714', '6694', '3638', '5113', '7804', '5465', '2226', '2015', '8480', '4536', '869', '2341', '5118', '2512', '2221', '6189', '1689', '6184', '1883', '3502', '7962', '6121', '7762', '5438', '814', '4196', '3337', '6256', '8455', '5627', '7618', '8228', '3634', '4000', '707_', '2038', '1687', '4616', '4879', '4592', '3806', '3537', '3718', '4501', '6091', '109', '6015', '2661', '6210', '4034', '4580', '6288', '7919', '5687', '8172', '6375', '5749', '3814', '3014', '7711', '8149', '2540', '819', '3507', '5514', '3766', '6754', '8279', '1525', '844_', '1310', '4458', '2127', '4575', '4936', '5938', '5643', '6219', '3790', '1990', '2580', '4860', '3413', '2939', '2987', '2756_', '7922', '1496', '8229', '7386', '2733', '5995', '2037_', '8035', '3385', '1925', '6456', '1144', '2024', '1407', '7082', '4279', '5327', '8516', '1133', '956', '1792', '1643', '5828', '8106', '1751', '6563', '5463', '6733', '8409', '7527', '3854', '924', '7065', '1441', '7641', '1733', '940', '8015', '8566', '2360', '5203', '5233', '1814', '6248', '5855', '6674', '6713', '5069', '3402', '1337', '6433', '6778', '902_', '6660', '3417', '429', '8150', '7746', '1958', '2309', '5413', '2113', '4706', '2116', '7776', '7240', '8090', '751', '7206', '2411', '1217', '3439', '715', '6786', '1817', '6321', '7524', '8448', '6794', '3789', '6501', '7868', '933', '8467', '4841', '8523_', '642', '5929', '1527', '1087', '8569', '347', '8503', '5301', '7725', '8295', '5027', '3640_', '7066', '5517', '4459', '7435', '3992', '1324', '6747', '3596', '5957', '2604', '3998_', '8125', '7392', '498', '3194', '3681', '6991', '3712_', '8037', '2097_', '3379', '7453', '1149', '8411', '8091', '6849', '1345', '8348_', '7900', '8127', '3873', '8616', '5425', '2507', '3004', '6579', '7157', '1537', '6577', '5588', '1996', '5748', '8473', '4926', '6113', '8370', '3103', '3913', '2106', '1842', '4287', '2558', '7255', '6632', '6763', '6460', '189', '434', '5730', '8485', '4548', '2821', '5793', '8036', '1136', '3765', '2525', '5020', '4566', '7151', '7792', '6775', '7808', '5164', '8286', '3326', '7663', '372', '1235', '2712', '4556', '1004', '2175', '1040', '6435', '4899', '7249', '6221', '1923', '5940', '4219', '3944', '6125', '6525', '2343', '3818', '7838', '4865', '5373_', '4988', '5222', '3291_', '3200', '8072', '7266', '2994_', '4271', '3339_', '2634', '6092', '2812_', '344', '6902', '5975', '448', '4601', '3332', '8547', '2926', '194', '3394', '7264', '8666', '5400', '2932', '7323', '8698', '3578_', '7733', '5419', '1461', '1405', '8199', '5603', '4921', '4007', '6191', '5361', '4189', '8381', '4568', '8100', '7967', '1289', '1443', '5121', '7579', '4781', '4190', '1664', '3564_', '6528', '3367', '7349', '535', '8422', '4318', '1306', '1362', '824', '3278', '2952', '1608', '8587', '6172', '7223', '3703', '6947', '8113', '6634', '5767', '5568', '6918', '806', '7493', '5931', '2405', '6843', '2928', '979', '1131', '8403', '1794_', '7849', '6736', '6696', '210', '6291', '4967', '5316', '8040', '2253', '7615', '2535', '5456', '2079', '6547', '5236', '5791', '1392', '5421', '3610', '4212', '1857', '4408', '4862', '5970', '4552', '7920', '6424', '737_', '2209', '4185', '672', '3048', '1172', '5247', '1696', '8470', '5629', '7139', '283', '6877', '5963', '1820', '2484', '4301_', '7610', '8288', '1202', '3167', '2919', '6295', '1485', '2638', '3720', '3213', '5939', '5184', '1858', '316', '2320', '6423', '7574', '6803', '5261', '509', '7256', '2846_', '7447', '4188', '7986', '1409', '5426', '7171', '2373_', '1188_', '1110', '4906', '2323', '1482', '4518', '6684', '7558', '5587', '6493', '5270', '4448', '1542', '5580', '7316', '4186', '3159', '7230', '2115', '8207_', '1515', '3617', '6392', '7271', '115', '960', '5909_', '6167', '8031', '8198', '6717', '3443', '6394', '3083', '7890', '2313', '1651', '1782', '1683', '6040', '1459', '2954', '8678', '488', '6140', '6381_', '4824', '2334', '7388', '8697', '5827', '1171', '3125', '2205', '504', '2318', '2351', '4475', '2178', '2381', '3361', '2809', '7201', '5988', '8616_', '6799_', '7342', '2659', '1591_', '7327', '817', '1460', '8640', '7681', '2249', '2104', '3775_', '7832', '4464', '3713', '5487', '2717', '8379', '6410', '4121', '3910', '6430', '4382', '8385', '1028', '2598', '1322', '1810', '4112', '2274', '6494', '2958', '8052', '7880', '6379', '2471', '8212', '3651', '6341', '725', '402', '8378', '2871', '146', '2357', '4089', '2160', '8069', '1022', '690', '383', '992', '7371', '5512', '5656', '6564_', '4574', '5153', '2543', '5101', '5840', '740', '3441', '6226', '5004', '1174', '681', '2880', '3988', '1900', '4252', '1154', '8481', '2128', '941', '4894', '246', '820', '8553', '6032', '6683', '2957', '7122_', '4913_', '6939', '6725', '1740', '4970', '4582', '594', '6814', '4422', '6165', '7768', '6086', '5219', '2321', '7489', '6287', '5509', '5697_', '985', '2626', '5422', '2955', '7799', '496', '4635', '1225', '1850', '3953', '6043', '2084', '3124', '5955', '3274', '7753', '1437', '5052', '4050', '3843_', '8046', '5778', '7236', '6914', '5122', '4521', '6254', '1583', '4929', '1368', '7973', '4041', '6212', '2108', '6912', '5140', '3689', '1939', '3919', '6190', '7523', '3855', '4227', '5541', '6596', '6199', '2620', '669', '2035', '5615', '4445_', '1794', '419', '6441', '1321', '8643', '5735', '3555', '3856', '462', '262', '6921_', '8088', '6355', '6665', '2630', '335', '6964', '6558', '6728', '2679', '3483', '8518', '1101', '7410', '1231', '4615', '6237', '1033', '7417', '4944', '6309', '1197', '962', '6099', '6990', '6364', '2074', '7476', '6117', '727', '3840', '7898', '7445', '6206', '3262', '2204', '1234', '7517', '4270', '2441', '780_', '952', '1394', '1200', '2765', '7886', '6839', '2840', '6007', '3904', '333', '598', '5602', '7462', '5973', '2855', '7481', '7638', '4347', '2875', '5063', '3155', '6618', '8297', '1953', '278', '8204', '7409', '5147', '7901', '5642', '6135', '920', '4402', '1070_', '8490', '5798_', '2406', '8315', '8425', '6476', '4808_', '2263', '1342']

**Observación:**
1. Algunos valores de `Age` tienen un guion bajo, que puede representar un error de tipeo (inconsistencia).
2. Se encuentran valores de edad negativos, lo que no es posible.
3. Aunque es posible que un cliente tenga más de 100 años, necesitamos establecer un rango.

In [19]:
# Substituimos los valores '_' por '' y los convertimos a tipo flotante ('float')
data['Age'] = data['Age'].replace('_', '', regex=True).astype('float') # regex=True para que reemplace todas las ocurrencias. regex means regular expression.

# Definimos un rango para los valores de la columna 'Age' de 1:100 y sustituimos los restantes con 'nan'
data.loc[data.Age < 1, 'Age'] = np.nan
data.loc[data.Age > 100, 'Age'] = np.nan

# Reemplazamos los valores 'nan' de la columna 'Age' con la media de la misma
data['Age'] = data['Age'].fillna(data['Age'].mean())

# Mostramos los valores únicos de la columna 'Age'
print(list(data['Age'].unique()))

# Mostramos el tipo de la columna 'Age'
print(data['Age'].dtype)

[23.0, 33.32327408870238, 28.0, 34.0, 54.0, 55.0, 21.0, 31.0, 33.0, 30.0, 24.0, 44.0, 45.0, 40.0, 41.0, 32.0, 35.0, 36.0, 39.0, 37.0, 20.0, 46.0, 26.0, 42.0, 19.0, 48.0, 38.0, 43.0, 22.0, 16.0, 18.0, 15.0, 27.0, 25.0, 14.0, 17.0, 47.0, 53.0, 56.0, 29.0, 49.0, 51.0, 50.0, 52.0, 99.0, 100.0, 95.0]
float64

#### Tratamiento de la columna `Occupation`

In [20]:
# Mostramos los valores únicos de la columna 'Occupation'
print(list(data['Occupation'].unique()))

['Scientist', '_______', 'Teacher', 'Engineer', 'Entrepreneur', 'Developer', 'Lawyer', 'Media_Manager', 'Doctor', 'Journalist', 'Manager', 'Accountant', 'Musician', 'Mechanic', 'Writer', 'Architect']

**Observación:**
1. Existe un valor '_______' que se debe eliminar.

In [57]:
# Substituimos el valor '_______' por 'nan' y los convertimos a tipo flotante ('float')
data['Occupation'] = data['Occupation'].replace('_______', np.nan, regex=True)

# Mostramos el número e valores 'nan' en la columna 'Occupation'
print(data['Occupation'].isna().sum())

7062

**Observación:**
1. Tenemos un número considerable de registros `NaN`. Tenemos dos opciones: i) Reemplazas los valores `NaN` con la moda, no perderás ningún registro. Pero en este contexto, estaríamos imponiendo una profesión a clientes que posiblemente no llenaron ese campo. ii) La segunda opción es eliminar los registros NaN, perderás esos registros, pero tus datos serán más precisos.

- Opción 1: Reemplazar los datos con la moda:

In [ ]:
# Calculamos la moda
# mode = data['Occupation'].mode()[0]
# mode

'Lawyer'

In [23]:
# Reemplazamos los valores NaN con la moda
# data['Occupation'].fillna(mode, inplace=True)

- Opción 2: Eliminar los registros NaN:

In [59]:
# Eliminamos los registros con valores NaN en la columna 'Occupation'
data.dropna(subset=['Occupation'], inplace=True)

**Eliminar columnas con muchos valores faltantes**: Si una columna tiene una gran cantidad de valores faltantes (~>70%), podría ser más útil eliminarla que intentar imputar los valores faltantes.

En este ejemplo, no existen columnas con más del 70% de valores faltantes. De existir, podemos eliminarla con el siguiente código:

In [25]:
# Eliminar columnas del DataFrame 'data' con más del 70% de valores faltantes
threshold = int(len(data) * 0.7) # Calcular el umbral de valores faltantes
data = data.dropna(thresh=threshold, axis=1) # Eliminar columnas con más del 70% de valores faltantes

**Reemplazar valores faltantes en columnas con pocos valores faltantes**: Los valores faltantes pueden ser identificados con el método `isnull()`. Para manejarlos, podemos usar la imputación (rellenar los valores faltantes con la media, mediana, o moda) o simplemente eliminar las filas con valores faltantes.

Para rellenar con la media los valores faltantes de las columnas numéricas con menos del 10% de valores faltantes, puedes usar la biblioteca pandas. Aquí te dejo un ejemplo de cómo hacerlo:

In [26]:
# DataFrame
for col in data.columns:
    if data[col].isnull().sum() / len(data) < 0.1:
        if data[col].dtype == 'float64' or data[col].dtype == 'int64':
            data[col].fillna(data[col].mean(), inplace=True)

# Mostramos el porcentaje de valores faltantes
data.isnull().mean()*100

/var/folders/8j/f0xtldm91_1c2bpdr69fxgzw0000gn/T/ipykernel_83369/2893222039.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[col].fillna(data[col].mean(), inplace=True)

Age                          0.000000
Occupation                   0.000000
Annual_Income                0.000000
Monthly_Inhand_Salary       15.001399
Num_Bank_Accounts            0.000000
Num_Credit_Card              0.000000
Interest_Rate                0.000000
Num_of_Loan                  0.000000
Type_of_Loan                11.344122
Delay_from_due_date          0.000000
Num_of_Delayed_Payment       6.985302
Changed_Credit_Limit         0.000000
Num_Credit_Inquiries         0.000000
Credit_Mix                   0.000000
Outstanding_Debt             0.000000
Credit_Utilization_Ratio     0.000000
Credit_History_Age           9.044740
Payment_of_Min_Amount        0.000000
Total_EMI_per_month          0.000000
Amount_invested_monthly      4.476102
Payment_Behaviour            0.000000
Monthly_Balance              1.210484
Credit_Score                 0.000000
dtype: float64



Este código recorre cada columna en el DataFrame. Si la columna tiene menos del 10% de valores faltantes y es numérica (es decir, su tipo de datos es 'float64' o 'int64'), entonces rellena los valores faltantes con la media de la columna.

La imputación de la media no es aplicable a las columnas de tipo string (categóricas). Para las columnas categóricas, puedes considerar diferentes métodos de imputación, como el más frecuente (moda), una constante o una cadena de texto específica como 'Desconocido'. Aquí te dejo un ejemplo de cómo hacerlo con pandas:

In [28]:
# Rellenar con la moda
categorical_columns = data.select_dtypes(include=[object]).columns # seleccionar columnas categóricas
data[categorical_columns] = data[categorical_columns].fillna(data[categorical_columns].mode().iloc[0]) # rellenar con la moda. iloc[0] se utiliza para seleccionar la primera fila del DataFrame resultante de mode(), que contiene el valor más frecuente para cada columna categórica. Esto asegura que se rellenen los valores faltantes con la moda correcta para cada columna.

**Columnas con alta correlación**: Si tienes dos columnas que están altamente correlacionadas, podrías considerar eliminar una de ellas. La razón es que ambas contienen información similar y tener ambas en el análisis podría introducir multicolinealidad.



Recuerda que estas son solo pautas generales y la decisión final de qué columnas eliminar debe basarse en el conocimiento del dominio y el objetivo de tu análisis.


**Codificación de Variables Categóricas**: Las variables categóricas como 'Occupation' y 'Type_of_Loan' deben ser codificadas antes de ser usadas en un modelo. Podrías usar codificación one-hot o codificación de etiquetas dependiendo de la naturaleza de los datos.

In [60]:
# Codificación one-hot
data_encoded = pd.get_dummies(data, columns=['Occupation', 'Type_of_Loan'])

In [63]:
data_encoded

,Age,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Delay_from_due_date,Num_of_Delayed_Payment,Changed_Credit_Limit,...,"Type_of_Loan_Student Loan, Student Loan, and Student Loan","Type_of_Loan_Student Loan, and Auto Loan","Type_of_Loan_Student Loan, and Credit-Builder Loan","Type_of_Loan_Student Loan, and Debt Consolidation Loan","Type_of_Loan_Student Loan, and Home Equity Loan","Type_of_Loan_Student Loan, and Mortgage Loan","Type_of_Loan_Student Loan, and Not Specified","Type_of_Loan_Student Loan, and Payday Loan","Type_of_Loan_Student Loan, and Personal Loan","Type_of_Loan_Student Loan, and Student Loan"
0,23,19114.12,1824.843333,3,4,3,4,3,7,11.27,...,False,False,False,False,False,False,False,False,False,False
1,23,19114.12,NaN,3,4,3,4,-1,NaN,11.27,...,False,False,False,False,False,False,False,False,False,False
2,-500,19114.12,NaN,3,4,3,4,3,7,_,...,False,False,False,False,False,False,False,False,False,False
3,23,19114.12,NaN,3,4,3,4,5,4,6.27,...,False,False,False,False,False,False,False,False,False,False
4,23,19114.12,1824.843333,3,4,3,4,6,NaN,11.27,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,25,39628.99,3359.415833,4,6,7,2,23,7,11.5,...,False,False,False,False,False,False,False,False,False,False
99996,25,39628.99,3359.415833,4,6,7,2,18,7,11.5,...,False,False,False,False,False,False,False,False,False,False
99997,25,39628.99,3359.415833,4,6,5729,2,27,6,11.5,...,False,False,False,False,False,False,False,False,False,False
99998,25,39628.99,3359.415833,4,6,7,2,20,NaN,11.5,...,False,False,False,False,False,False,False,False,False,False
99999,25,39628.99_,3359.415833,4,6,7,2,18,6,11.5,...,False,False,False,False,False,False,False,False,False,False

**Escalado de Características**: Las características como 'Annual_Income', 'Monthly_Inhand_Salary', 'Outstanding_Debt' podrían tener diferentes rangos y podrían necesitar ser escaladas.

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
data_scaled = scaler.fit_transform(data[['Annual_Income', 'Monthly_Inhand_Salary', 'Outstanding_Debt']])

**Selección de Características**: Podrías usar métodos como la correlación de Pearson para identificar las variables más relevantes para tu variable objetivo.

In [ ]:
correlation = data.corr()
correlation['Credit_Score'].sort_values(ascending=False)


#### Identificación y Manejo de Outliers

Los outliers pueden ser identificados utilizando métodos estadísticos, como el método del rango intercuartil (IQR). Una vez identificados, pueden ser eliminados o ajustados.

In [ ]:
# Identificar outliers con el método IQR
Q1 = data.quantile(0.25)
Q3 = data.quantile(0.75)
IQR = Q3 - Q1

# Eliminar outliers
data = data[~((data < (Q1 - 1.5 * IQR)) | (data > (Q3 + 1.5 * IQR))).any(axis=1)]

#### Identificación y Manejo de Datos Inconsistentes

Los datos inconsistentes pueden ser identificados revisando los valores únicos de cada característica. Una vez identificados, pueden ser corregidos o eliminados.

In [33]:
# Identificar datos inconsistentes
for column in data.columns:
    print(data[column].unique())

[ 23.          33.32327409  28.          34.          54.
  55.          21.          31.          33.          30.
  24.          44.          45.          40.          41.
  32.          35.          36.          39.          37.
  20.          46.          26.          42.          19.
  48.          38.          43.          22.          16.
  18.          15.          27.          25.          14.
  17.          47.          53.          56.          29.
  49.          51.          50.          52.          99.
 100.          95.        ]
['Scientist' 'Teacher' 'Engineer' 'Entrepreneur' 'Developer' 'Lawyer'
 'Media_Manager' 'Doctor' 'Journalist' 'Manager' 'Accountant' 'Musician'
 'Mechanic' 'Writer' 'Architect']
['19114.12' '34847.84' '34847.84_' ... '20002.88' '39628.99' '39628.99_']
[1824.84333333           nan 3037.98666667 ... 3097.00833333 1929.90666667
 3359.41583333]
[   3    2    1    7    4    0    8    5    6    9   10 1414 1231   67
 1488   91  528 1647 1696 1338  649  889 1668  685  857  975 1496 1534
 1620   37 1388 1429 1332 1588  120 1777 1096  803  494  744 1139  831
 1613  741  121 1748 1644  823 1356 1651   87  711  450  210 1671 1722
  648  672 1662 1495  510  666  429 1131 1434 1026  526  718 1300 1312
 1315  501 1566  480 1042  322 1016  333 1265  563  905 1190 1036 1611
   38  555 1769  280  752 1201  812 1487  222  212 1019 1222  610 1308
  525 1158 1115 1616  754 1601  797  521  703  933  959  809 1089 1656
 1113 1715  964 1789  871  434 1295  565 1724  603  677  541  698 1101
 1539 1462 1011 1727   45  244 1266  897  331  675  826  946 1675  105
 1327  845  473  710  527  908   68 1628  371  445 1168  868  687  455
 1003   26 1526  618  351 1342 1783  791  683 1557 1335  416 1747  137
 1475 1257  373  338  942  170  973 1605 1478  386 1448 1033 1225 1731
 1214 1481 1105  580  347  108  148 1001 1467 1114  632  246 1032 1394
  689  482 1303  720  574  588 1358  650  708  179  844 1577   60  732
 1494 1436  820   28 1576  818  794  534  556  691 1197 1155 1255 1763
  769 1124  819  318 1418  882   61  264  194 1798  611  840  505 1110
  719 1065  195  584  550 1014 1022  903  976   31  417 1423  616  786
 1424   55 1061  342   43 1540  488 1122 1274 1075  722 1268   41  814
 1564 1390 1141  497  224 1135  374   74  314 1408  475 1015  681 1236
 1425 1637 1240  299 1123 1091 1264 1561 1632 1562  305 1318 1217 1699
 1070 1391  112  860  595  229 1624 1051  821 1794 1565  397 1368 1353
  508 1725 1413 1239  847 1317  570   -1  302  456  198  122  832  167
 1547 1666 1241  275  566 1779  201  334 1169  834 1174 1040  530 1676
 1468 1093  706 1592  688  830 1784 1543 1600  228  483 1501  950  870
 1211  604  804  129 1702 1636 1680 1443 1252  180  702  885 1652  795
  938 1654 1793  303 1621 1516 1138   32  160   83  423  928  339  243
 1756  540  583 1695  274  955  430  441 1247  490  726  987   42 1626
 1470 1739  887  211  385 1221  324  406 1677 1567  785 1079 1771 1048
 1069  589 1634   70 1371  647 1153  239  801 1279 1287  425 1589  929
 1511 1047 1005 1337  981 1766  805 1574 1638  186   99  288  974  996
 1595 1594  865  203 1440  448  285   94  875  916  240  330   79   82
  135 1043  142 1235 1569 1741 1461 1551  409  418 1017  892  124  935
  313 1363  232 1184 1432 1479 1407 1080 1719 1024  970  761  158 1060
  684  696 1502  936  560  485  464  350 1560 1166 1013   34 1691  715
 1570  535 1751 1503 1194 1558  411  298  260  308  796 1442  912 1256
  746  435  620 1774 1323  837  307 1430 1447  259  921  328 1034  353
  822  654  609  136  172 1306 1028  270 1072  514  156 1331 1630  462
 1310 1210  265   50 1355  394 1393  226  991  368 1018 1037  627 1744
  523  894  944 1730 1076 1094 1617  449  678 1164  312   30  817  607
  709 1230  606 1480   29 1522 1670   49  626 1712 1370 1782  119 1137
 1277   35  851 1041 1583 1536  575  196  143   33  383   57  621  230
  162 1504 1250   39  511 1364  918 1665  734  316  771  705 1435  304
  116 1553  424  493 1530 1195 1604  624 1599  782 1606 1622 1285  657
 1275 1291 1402  420  468  442 1145   93 1218  166  283  292  927 1711
 1422  364 1398  594  789 1350  676  216 1012 1426  717 1095 1786  850
  777  375  356  701 1325  290 1352 1775  467 1365 1549  848 1453   84
 1458  888  770 1591  582   40 1261 1764 1067  145  471  476 1128  967
  622  641  539  295  354 1395 1517 1297 1126  926 1377  993  125  340
  271  272  979  707  564  997  447 1578 1465  415  714 1276   18 1316
 1320  587  245 1650  446  978 1002 1631  341 1307 1267  103  242 1378
 1328 1294 1309  724  197  999  547 1100 1456   77 1506 1472  460   11
 1420  549  218 1253  392  670 1321  100  443   92  811  774  159 1770
  972 1157 1102  217  358 1473  864  440  140 1361  481  512 1117  300
 1263 1581  901 1298  310  637  758 1734 1288  326 1678 1444 1344 1379
  828  982  104  317 1529 1627  115  645 1404  940 1305 1049 1645 1466
  175 1165 1419  581 1714 1580  854 1655 1134  569 1387 1381 1760  360
 1735 1146 1411  969 1281  591  327  466  667  147  109  784 1396 1349
  931 1284  802   97  281 1382 1039 1483  376 1249 1207 1213 1219 1345
 1523  949 1063  983  886 1151  992 1107 1314  151 1489  695  738  444
 1525  825  506  518 1077 1354  713  690  861 1389  968  421  907  205
  596  856   72  651  161  867  971 1078 1701  546 1216   27 1709  193
  957  577  346 1416  396 1733 1182  652 1778  680 1754 1544 1703  636
  472  453  463 1083   75  756  296  891  813  474  697  182]
[   4 1385    5 ...  686  955  679]
[   3    6    8 ... 1347  387 5729]
['4' '1' '3' '967' '-100' '0' '0_' '2' '3_' '2_' '7' '5' '5_' '6' '8' '8_'
 '9' '9_' '4_' '7_' '1_' '1464' '6_' '622' '352' '1017' '146' '563' '341'
 '444' '720' '49' '737' '1106' '466' '728' '313' '843' '597_' '617' '119'
 '663' '640' '92_' '1019' '501' '1302' '39' '716' '848' '931' '1214' '186'
 '424' '1001' '1110' '1152' '457' '1433' '1187' '52' '1480' '1047' '1035'
 '1347_' '193' '699' '329' '1451' '484' '132' '649' '995' '545' '684'
 '1135' '1094' '654' '58' '348' '614' '1363' '323' '1406' '1348' '430'
 '153' '1461' '905' '1312' '1424' '95' '1353' '1228' '819' '1006' '795'
 '359' '1209' '590' '696' '1185_' '1465' '911' '1181' '70' '816' '1369'
 '143' '1416' '455' '55' '1096' '1474' '420' '1131' '904' '89' '1259'
 '527' '1241' '449' '418' '23' '238' '638' '138' '235_' '280' '1070'
 '1484' '274' '494' '1459_' '404' '1354' '1495' '1391' '601' '1319' '898'
 '231' '752' '174' '961' '1046' '834' '284' '438' '288' '1463' '1151'
 '719' '198' '1015' '855' '841' '1444' '103' '1320_' '745' '252' '630_'
 '241' '31' '405' '1217' '1030' '1257' '172' '137' '157' '164' '1088'
 '1048' '330' '1439' '321' '661' '952' '939' '562' '1202' '302' '943'
 '394' '955' '1318' '936' '781' '100' '1329' '1365' '860' '217' '191' '32'
 '282' '351' '1387' '757' '416' '833' '359_' '292' '1225_' '1227' '639'
 '859' '243' '267' '510' '332' '597' '311' '492' '820' '336' '123' '1311_'
 '1441' '895' '50' '940' '935' '596' '29' '1182' '1129_' '1014' '251'
 '365' '291' '1447' '742' '1085' '148' '462' '832' '881' '1225' '1412'
 '785_' '1127' '910' '538' '999' '733' '101' '237' '659' '633' '387' '447'
 '629' '831' '1384' '773' '621' '1419' '143_' '285' '1393' '1131_' '27_'
 '1359' '1482' '1189' '1294' '201' '579' '814' '141' '1320' '581' '1171_'
 '679' '1040' '1054' '1430' '1023' '1077' '1457' '1150' '701' '1382' '889'
 '437' '372' '1222' '126' '1159' '868' '19' '1297' '227_' '190' '809'
 '1216' '1074' '571' '520' '1274' '1340' '316' '697' '926' '1002' '378_'
 '65' '875' '867' '548' '652' '33' '1372' '606' '1036' '1300' '17' '1178'
 '290' '802' '1219_' '1271' '1236' '1137' '1496' '439' '196' '192' '228'
 '1053' '229' '753' '1296' '1371' '254' '863' '464' '515' '838' '1160'
 '1289' '1298' '799' '574' '527_' '242' '415' '869' '958' '54' '1265'
 '656' '275' '778' '208' '147' '507' '463' '497' '927' '653' '662' '529'
 '1027_' '897' '1039' '227' '1345' '924' '696_' '1279' '546' '1112' '1210'
 '526' '300' '1103' '504' '136' '1400' '78' '686' '1091' '344' '215' '84'
 '628' '1470' '968' '83' '1196' '1307' '1132_' '1008' '917' '657' '56'
 '18' '41' '801' '978' '216' '349' '966']
['Auto Loan, Credit-Builder Loan, Personal Loan, and Home Equity Loan'
 'Credit-Builder Loan' 'Auto Loan, Auto Loan, and Not Specified' ...
 'Home Equity Loan, Auto Loan, Auto Loan, and Auto Loan'
 'Payday Loan, Student Loan, Mortgage Loan, and Not Specified'
 'Personal Loan, Auto Loan, Mortgage Loan, Student Loan, and Student Loan']
[ 3 -1  5  6  8  7 13  0  4  9  1 10 12 11 30 31 14  2 -2 16 17 15 23 22
 21 18 19 52 51 48 53 26 43 28 25 20 47 46 49 61 29 50 58 45 27 59 55 56
 57 54 62 65 64 36 41 24 33 32 39 44 60 35 34 38 63 42 40 37 -3 -5 -4 66
 67]
['7' '19' '4' '8_' '6' '1' '-1' '3_' '0' '5' '3' '9' '12' '15' '17' '10'
 '2' '2_' '11' '14' '8' '20' '22' '13' '13_' '14_' '16' '12_' '18' '23'
 '21' '24' '3318' '3083' '22_' '1338' '4_' '3104' '21_' '25' '10_' '183_'
 '9_' '1106' '834' '19_' '26' '24_' '17_' '23_' '2672' '20_' '2008' '-3'
 '538' '1_' '16_' '-2' '3478' '2420' '15_' '707' '708' '26_' '18_' '3815'
 '11_' '28' '27' '5_' '1867' '2250' '1463' '25_' '7_' '4126' '2882' '1941'
 '2628' '132' '3069' '306' '0_' '6_' '3539' '3684' '1823' '4128' '1946'
 '827' '2297' '2566' '904' '182' '929' '3568' '2503' '1552' '2812' '1697'
 '851' '3905' '923' '88' '1668' '3253' '808' '2689' '3858' '642' '3457'
 '1402' '1732' '3154' '847' '3037' '2204' '3103' '1063' '2056' '1282'
 '2569_' '211' '793' '3484' '411' '3491' '2072' '3050' '1049' '2162'
 '3402' '27_' '1718' '1014' '3260' '3855' '84' '2311' '3251' '1832' '4069'
 '3010' '733' '4241' '166' '2461' '1749' '3200' '663_' '2185' '4161'
 '3009' '359' '2015' '1523' '594' '1199' '186' '1015' '1989' '281' '559'
 '2165' '1509' '3545' '779' '192' '-2_' '2323' '1471' '1538' '3529' '3456'
 '3040' '2697' '3179' '1332' '3175' '3112' '829' '4022' '3870' '4023'
 '531' '3092' '3191' '2400' '3621' '3536' '544' '1864' '28_' '142' '2300'
 '264' '72' '497' '398' '2222' '3960' '1473' '3043' '4216' '2903' '2658'
 '-1_' '1323_' '2184' '921' '1328' '3404' '2438' '809' '47' '1996' '4164'
 '1370' '1204' '2167' '4011' '2594' '2533' '1663' '1018' '2919' '3316'
 '2589' '2801' '3355' '2529' '2488' '4266' '1243' '739' '845' '4107'
 '1884' '2660' '290' '674' '2450' '3738' '1792' '2823' '775' '960' '1706'
 '2493' '3031' '2794_' '2219_' '758_' '1849' '3559' '4096' '3726' '1953'
 '2657' '4043' '2938' '4384' '1647' '2694' '3533' '519' '2677' '2413'
 '-3_' '4139' '2609' '4326' '4211' '823' '3011' '1608' '2860' '4219'
 '4047' '1531' '742' '52' '4024' '1673' '49' '2243' '1685' '2587' '3489'
 '749' '1164' '2616' '848_' '4134' '1530' '1502' '4075' '3845' '1060'
 '2573' '2128' '640' '2585' '2230' '1795' '1180' '1534' '3739' '3313'
 '4191' '996' '372' '3340' '3177' '602' '787' '4135' '3878' '4059' '1766'
 '1359' '3107' '1263' '2511' '709' '3632' '4077' '2943' '2793' '2317'
 '1640' '2237_' '3819' '252' '3978' '1833' '2737' '1192' '1481' '271'
 '2286' '273' '1215' '3944' '2070' '1478' '3749' '871' '2508' '2959' '130'
 '294' '3097_' '3511' '415' '2196' '2138' '2149' '1874' '1553' '3847'
 '3222' '1222' '2907' '3051' '98' '1598' '416' '2314' '2955' '1691' '1450'
 '2021' '1636' '80' '3708' '195' '320' '2945' '1911' '3416' '3796' '2255'
 '938' '4397' '3776' '2148' '1994' '853' '1178' '1633' '3864' '714' '1687'
 '1034' '468' '1337' '2044' '1541' '3661' '1211' '2645' '2007' '102'
 '1891' '3162' '3142' '2566_' '2766' '3881' '2728' '1952' '3580' '2705'
 '3840_' '972' '3119' '3502' '4185' '2954' '683' '1614' '1572' '4302'
 '3447' '1852' '2131' '1900' '1699' '133' '2018' '2127' '508' '577' '1664'
 '2604' '1411' '2351' '1371' '2352' '1191' '905' '4053' '3869' '933'
 '3660' '3300' '3629' '3208' '2142' '2521' '450' '583' '876' '121' '3919'
 '2560' '2578' '2060' '1236' '1489' '4360' '1154' '2544' '4172' '2924'
 '4270' '3909' '3951' '2712' '2498' '3171' '1750' '197' '2569' '265'
 '4293' '887' '2707' '2397' '4337' '4249' '2950' '1859' '107' '2348'
 '2506' '2810' '2873' '1301' '2262' '1890' '3078' '3865' '3268' '3105'
 '1278' '3793' '2276' '2879' '4298' '2141' '223' '2239' '846' '1862'
 '2756' '1181' '1184' '2617' '3972' '2334' '3900' '2759' '4169' '2280'
 '2492' '2729' '3750' '1825' '309' '2431' '3099' '2080' '2279' '2666'
 '3722' '1976' '529' '1985' '3060' '4278' '3212' '3148' '3467' '3790'
 '473' '1536' '3955' '2324' '2381' '1177' '371' '2896' '3880' '2991'
 '4319' '1061' '662' '4144' '693' '2006' '3115' '3751' '1861' '4262'
 '2913' '3492' '800' '3766' '384' '3407' '1087' '1086' '2216' '1087_'
 '3522' '3274' '3488' '238' '351' '3706' '4280' '4095' '2926' '1329'
 '3370' '283' '1392' '2429' '974' '3156' '1133' '4388' '3243' '4282'
 '2523' '4281' '3415' '2001' '441' '94' '3499' '969' '3368' '1004' '2638'
 '3946' '2956' '4324' '85' '4113' '819' '1172' '2553' '1765' '3495' '4239'
 '4340' '1295_' '2636' '4295' '1653' '1325' '1879' '1096' '1735' '3584'
 '1975' '3827' '2552' '3754' '2378' '532' '926' '2376' '3636' '3763' '778'
 '2621' '804' '754' '2418' '4019' '3926' '3861_' '3574' '175' '162' '2834'
 '3765' '523' '2274' '1606' '1443' '1354' '2142_' '1422' '4231' '2278'
 '1045' '4106' '3155' '666' '659' '3229' '1841' '1216' '2076' '1473_'
 '2384' '1954' '719' '2534' '4002' '541' '2875' '4344' '2081' '3894'
 '1256' '676' '4178' '399' '86' '1571' '4037' '1967' '4005' '2671' '1150'
 '2591' '1801' '3721' '1775' '2260' '3707' '4292' '1820' '145' '1480'
 '1850' '430' '217' '3920_' '1389' '1579' '3391' '2385' '3336' '3392'
 '3688' '221' '2047']
['11.27' '_' '6.27' ... '17.509999999999998' '25.16' '21.17']
[  4.   2.   3. ... 310.  93.  74.]
['_' 'Good' 'Standard' 'Bad']
['809.98' '605.03' '1303.01' ... '3571.7_' '3571.7' '502.38']
[26.82261962 31.94496006 28.60935202 ... 41.25552226 33.63820798
 34.19246265]
['22 Years and 1 Months' '15 Years and 11 Months' '22 Years and 3 Months'
 '22 Years and 4 Months' '22 Years and 5 Months' '22 Years and 6 Months'
 '22 Years and 7 Months' '26 Years and 8 Months' '26 Years and 9 Months'
 '26 Years and 10 Months' '26 Years and 11 Months' '27 Years and 0 Months'
 '27 Years and 1 Months' '27 Years and 2 Months' '17 Years and 10 Months'
 '18 Years and 2 Months' '18 Years and 3 Months' '18 Years and 4 Months'
 '17 Years and 3 Months' '17 Years and 4 Months' '17 Years and 5 Months'
 '17 Years and 6 Months' '17 Years and 7 Months' '17 Years and 9 Months'
 '30 Years and 8 Months' '30 Years and 9 Months' '30 Years and 10 Months'
 '30 Years and 11 Months' '31 Years and 0 Months' '31 Years and 1 Months'
 '31 Years and 2 Months' '31 Years and 3 Months' '32 Years and 2 Months'
 '32 Years and 3 Months' '32 Years and 5 Months' '32 Years and 6 Months'
 '30 Years and 7 Months' '14 Years and 8 Months' '14 Years and 9 Months'
 '15 Years and 0 Months' '15 Years and 1 Months' '15 Years and 2 Months'
 '21 Years and 4 Months' '21 Years and 5 Months' '21 Years and 6 Months'
 '21 Years and 7 Months' '21 Years and 8 Months' '21 Years and 9 Months'
 '21 Years and 10 Months' '21 Years and 11 Months' '26 Years and 6 Months'
 '26 Years and 7 Months' '19 Years and 2 Months' '19 Years and 3 Months'
 '19 Years and 5 Months' '19 Years and 6 Months' '19 Years and 7 Months'
 '19 Years and 8 Months' '25 Years and 5 Months' '25 Years and 6 Months'
 '25 Years and 7 Months' '25 Years and 8 Months' '25 Years and 9 Months'
 '25 Years and 10 Months' '25 Years and 11 Months' '26 Years and 0 Months'
 '27 Years and 3 Months' '27 Years and 4 Months' '27 Years and 5 Months'
 '8 Years and 11 Months' '9 Years and 0 Months' '9 Years and 1 Months'
 '9 Years and 2 Months' '9 Years and 3 Months' '9 Years and 4 Months'
 '9 Years and 6 Months' '18 Years and 5 Months' '18 Years and 6 Months'
 '18 Years and 8 Months' '18 Years and 9 Months' '16 Years and 10 Months'
 '16 Years and 11 Months' '17 Years and 0 Months' '17 Years and 1 Months'
 '17 Years and 2 Months' '29 Years and 2 Months' '29 Years and 3 Months'
 '29 Years and 4 Months' '29 Years and 6 Months' '29 Years and 8 Months'
 '29 Years and 9 Months' '6 Years and 5 Months' '6 Years and 6 Months'
 '6 Years and 7 Months' '6 Years and 8 Months' '6 Years and 9 Months'
 '6 Years and 10 Months' '6 Years and 11 Months' '7 Years and 0 Months'
 '27 Years and 6 Months' '27 Years and 7 Months' '27 Years and 8 Months'
 '27 Years and 9 Months' '19 Years and 4 Months' '19 Years and 9 Months'
 '19 Years and 10 Months' '10 Years and 1 Months' '10 Years and 2 Months'
 '10 Years and 3 Months' '10 Years and 4 Months' '10 Years and 5 Months'
 '10 Years and 7 Months' '10 Years and 8 Months' '32 Years and 9 Months'
 '32 Years and 10 Months' '32 Years and 11 Months' '33 Years and 0 Months'
 '33 Years and 1 Months' '33 Years and 4 Months' '12 Years and 3 Months'
 '12 Years and 4 Months' '12 Years and 5 Months' '12 Years and 7 Months'
 '12 Years and 8 Months' '12 Years and 10 Months' '12 Years and 6 Months'
 '12 Years and 9 Months' '18 Years and 1 Months' '13 Years and 8 Months'
 '13 Years and 11 Months' '14 Years and 1 Months' '14 Years and 2 Months'
 '14 Years and 3 Months' '30 Years and 3 Months' '30 Years and 4 Months'
 '30 Years and 6 Months' '8 Years and 9 Months' '8 Years and 10 Months'
 '18 Years and 7 Months' '18 Years and 10 Months' '18 Years and 11 Months'
 '19 Years and 0 Months' '19 Years and 1 Months' '8 Years and 8 Months'
 '13 Years and 1 Months' '13 Years and 2 Months' '13 Years and 3 Months'
 '13 Years and 5 Months' '13 Years and 6 Months' '13 Years and 7 Months'
 '22 Years and 0 Months' '26 Years and 1 Months' '26 Years and 2 Months'
 '13 Years and 4 Months' '13 Years and 9 Months' '27 Years and 11 Months'
 '28 Years and 0 Months' '28 Years and 1 Months' '28 Years and 4 Months'
 '28 Years and 5 Months' '7 Years and 10 Months' '7 Years and 11 Months'
 '8 Years and 0 Months' '8 Years and 1 Months' '8 Years and 2 Months'
 '8 Years and 3 Months' '8 Years and 4 Months' '8 Years and 5 Months'
 '24 Years and 3 Months' '24 Years and 4 Months' '24 Years and 5 Months'
 '24 Years and 6 Months' '24 Years and 7 Months' '24 Years and 8 Months'
 '24 Years and 9 Months' '17 Years and 8 Months' '1 Years and 2 Months'
 '1 Years and 3 Months' '1 Years and 4 Months' '1 Years and 5 Months'
 '1 Years and 6 Months' '1 Years and 7 Months' '1 Years and 8 Months'
 '10 Years and 11 Months' '11 Years and 0 Months' '11 Years and 3 Months'
 '11 Years and 4 Months' '11 Years and 5 Months' '11 Years and 6 Months'
 '19 Years and 11 Months' '20 Years and 0 Months' '20 Years and 1 Months'
 '10 Years and 6 Months' '10 Years and 9 Months' '10 Years and 10 Months'
 '14 Years and 0 Months' '14 Years and 4 Months' '14 Years and 5 Months'
 '20 Years and 8 Months' '20 Years and 9 Months' '20 Years and 10 Months'
 '20 Years and 11 Months' '21 Years and 0 Months' '21 Years and 2 Months'
 '21 Years and 3 Months' '0 Years and 4 Months' '0 Years and 5 Months'
 '0 Years and 6 Months' '0 Years and 8 Months' '0 Years and 9 Months'
 '0 Years and 10 Months' '31 Years and 7 Months' '31 Years and 8 Months'
 '31 Years and 9 Months' '31 Years and 10 Months' '31 Years and 11 Months'
 '32 Years and 0 Months' '32 Years and 1 Months' '12 Years and 11 Months'
 '13 Years and 0 Months' '27 Years and 10 Months' '11 Years and 7 Months'
 '11 Years and 8 Months' '11 Years and 10 Months' '24 Years and 10 Months'
 '24 Years and 11 Months' '25 Years and 0 Months' '25 Years and 2 Months'
 '25 Years and 3 Months' '17 Years and 11 Months' '18 Years and 0 Months'
 '31 Years and 4 Months' '31 Years and 5 Months' '5 Years and 2 Months'
 '5 Years and 3 Months' '5 Years and 4 Months' '5 Years and 5 Months'
 '5 Years and 6 Months' '5 Years and 7 Months' '5 Years and 8 Months'
 '5 Years and 9 Months' '2 Years and 11 Months' '3 Years and 0 Months'
 '3 Years and 1 Months' '3 Years and 3 Months' '3 Years and 4 Months'
 '3 Years and 5 Months' '3 Years and 6 Months' '16 Years and 4 Months'
 '16 Years and 5 Months' '16 Years and 6 Months' '16 Years and 8 Months'
 '22 Years and 11 Months' '23 Years and 0 Months' '23 Years and 2 Months'
 '23 Years and 3 Months' '23 Years and 4 Months' '23 Years and 5 Months'
 '23 Years and 6 Months' '8 Years and 6 Months' '4 Years and 5 Months'

#### Balanceo de Datos

El balanceo de datos puede ser necesario si nuestra variable objetivo está desbalanceada. Podemos usar técnicas como el oversampling o el undersampling.

In [ ]:
from imblearn.over_sampling import SMOTE

smote = SMOTE()
X_res, y_res = smote.fit_resample(data.drop('target', axis=1), data['target'])

#### Discretización

La discretización convierte las variables continuas en variables discretas.

In [ ]:
data['age'] = pd.cut(data['age'], bins=3, labels=['young', 'middle-aged', 'old'])



Finalmente, podemos usar una regresión lineal (o cualquier otro modelo de aprendizaje automático) para predecir si a un cliente se le otorgará crédito o no.

In [ ]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_res, y_res)



Este tutorial es solo una introducción a las técnicas de procesamiento y transformación de datos. Hay muchas otras técnicas y métodos disponibles, y la elección de las técnicas a utilizar dependerá de la naturaleza de tus datos y del problema que estés tratando de resolver.

## **No time?** Try this...

In [65]:
import pandas as pd
data = pd.read_csv('/Users/eugenio/Documents/Notebooks_ArtificialIntelligence/Datasets/credit_score.csv')
data = data.drop(['ID', 'Customer_ID', 'Month', 'Name', 'SSN',], axis=1)
data.head()

/var/folders/8j/f0xtldm91_1c2bpdr69fxgzw0000gn/T/ipykernel_83369/3576933381.py:2: DtypeWarning: Columns (26) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('/Users/eugenio/Documents/Notebooks_ArtificialIntelligence/Datasets/credit_score.csv')

,Age,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Type_of_Loan,Delay_from_due_date,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
0,23,Scientist,19114.12,1824.843333,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",3,...,_,809.98,26.822620,22 Years and 1 Months,No,49.574949,80.41529543900253,High_spent_Small_value_payments,312.49408867943663,Good
1,23,Scientist,19114.12,NaN,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",-1,...,Good,809.98,31.944960,NaN,No,49.574949,118.28022162236736,Low_spent_Large_value_payments,284.62916249607184,Good
2,-500,Scientist,19114.12,NaN,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",3,...,Good,809.98,28.609352,22 Years and 3 Months,No,49.574949,81.699521264648,Low_spent_Medium_value_payments,331.2098628537912,Good
3,23,Scientist,19114.12,NaN,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",5,...,Good,809.98,31.377862,22 Years and 4 Months,No,49.574949,199.4580743910713,Low_spent_Small_value_payments,223.45130972736786,Good
4,23,Scientist,19114.12,1824.843333,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",6,...,Good,809.98,24.797347,22 Years and 5 Months,No,49.574949,41.420153086217326,High_spent_Medium_value_payments,341.48923103222177,Good

In [36]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 23 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   Age                       100000 non-null  object
 1   Occupation                100000 non-null  object
 2   Annual_Income             100000 non-null  object
 3   Monthly_Inhand_Salary     84998 non-null   float64
 4   Num_Bank_Accounts         100000 non-null  int64
 5   Num_Credit_Card           100000 non-null  int64
 6   Interest_Rate             100000 non-null  int64
 7   Num_of_Loan               100000 non-null  object
 8   Type_of_Loan              88592 non-null   object
 9   Delay_from_due_date       100000 non-null  int64
 10  Num_of_Delayed_Payment    92998 non-null   object
 11  Changed_Credit_Limit      100000 non-null  object
 12  Num_Credit_Inquiries      98035 non-null   float64
 13  Credit_Mix                100000 non-null  object
 14  Outstanding_Debt          100000 non-null  object
 15  Credit_Utilization_Ratio  100000 non-null  float64
 16  Credit_History_Age        90970 non-null   object
 17  Payment_of_Min_Amount     100000 non-null  object
 18  Total_EMI_per_month       100000 non-null  float64
 19  Amount_invested_monthly   95521 non-null   object
 20  Payment_Behaviour         100000 non-null  object
 21  Monthly_Balance           98800 non-null   object
 22  Credit_Score              100000 non-null  object
dtypes: float64(4), int64(4), object(15)
memory usage: 17.5+ MB

In [37]:
# Identify categorical columns
cat_cols = data.select_dtypes(include=["object"]).columns
print(cat_cols)

Index(['Age', 'Occupation', 'Annual_Income', 'Num_of_Loan', 'Type_of_Loan',
       'Num_of_Delayed_Payment', 'Changed_Credit_Limit', 'Credit_Mix',
       'Outstanding_Debt', 'Credit_History_Age', 'Payment_of_Min_Amount',
       'Amount_invested_monthly', 'Payment_Behaviour', 'Monthly_Balance',
       'Credit_Score'],
      dtype='object')

In [67]:
# clean categorical columns
for col in cat_cols:
    data[col] = data[col].str.strip().str.lower() # .strip removes leading and trailing whitespace, and .lower() converts to lowercase
    data[col] = data[col].replace(["?", "na", "none", "null", "","_","_______"], pd.NA)
    mode = data[col].mode()[0] 
    data[col].fillna(mode, inplace=True)

/var/folders/8j/f0xtldm91_1c2bpdr69fxgzw0000gn/T/ipykernel_83369/2427841289.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[col].fillna(mode, inplace=True)

In [39]:
data.shape

(100000, 23)

In [68]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for col in cat_cols:
    data[col] = data[col].astype(str) # avoid errors with NA
    data[col] = le.fit_transform(data[col])

In [41]:
data.shape

(100000, 23)

In [69]:
# Apply coerce to all numeric columns
for col in data.select_dtypes(include=["number"]).columns:
    data[col] = pd.to_numeric(data[col], errors='coerce') # errors='coerce' will convert invalid parsing to NaN

In [70]:
# Mean imputation
for col in data.select_dtypes(include=['float64', 'int64']).columns:
    data[col].fillna(data[col].mean(), inplace=True)

/var/folders/8j/f0xtldm91_1c2bpdr69fxgzw0000gn/T/ipykernel_83369/3347571600.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[col].fillna(data[col].mean(), inplace=True)

In [44]:
data.shape

(100000, 23)

In [71]:
# Label isolation
X = data.drop('Credit_Score', axis=1)
y = data['Credit_Score']

# Data splitting
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Model fitting
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(
    n_estimators=100,
    max_depth=5,
    random_state=42
)
model.fit(X_train, y_train)

# Model prediction
y_pred = model.predict(X_test)

# Model evaluation
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.58      0.39      0.47      3527
           1       0.65      0.65      0.65      5874
           2       0.66      0.74      0.70     10599

    accuracy                           0.65     20000
   macro avg       0.63      0.59      0.61     20000
weighted avg       0.65      0.65      0.64     20000