In [2]:
# read the dataset credit_score.csv in pandas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:

# Read the dataset
df = pd.read_csv('/Users/eugenio/Documents/Notebooks_ArtificialIntelligence/Datasets/credit_score.csv')

In [3]:
# Muestra las primeras filas del dataframe
df.head()

,ID,Customer_ID,Month,Name,Age,SSN,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
0,0x1602,CUS_0xd40,January,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,...,_,809.98,26.822620,22 Years and 1 Months,No,49.574949,80.41529543900253,High_spent_Small_value_payments,312.49408867943663,Good
1,0x1603,CUS_0xd40,February,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,NaN,3,...,Good,809.98,31.944960,NaN,No,49.574949,118.28022162236736,Low_spent_Large_value_payments,284.62916249607184,Good
2,0x1604,CUS_0xd40,March,Aaron Maashoh,-500,821-00-0265,Scientist,19114.12,NaN,3,...,Good,809.98,28.609352,22 Years and 3 Months,No,49.574949,81.699521264648,Low_spent_Medium_value_payments,331.2098628537912,Good
3,0x1605,CUS_0xd40,April,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,NaN,3,...,Good,809.98,31.377862,22 Years and 4 Months,No,49.574949,199.4580743910713,Low_spent_Small_value_payments,223.45130972736786,Good
4,0x1606,CUS_0xd40,May,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,...,Good,809.98,24.797347,22 Years and 5 Months,No,49.574949,41.420153086217326,High_spent_Medium_value_payments,341.48923103222177,Good

In [4]:
#Divide la base de datos en dos conjuntos: uno para entrenamiento y otro para prueba
from sklearn.model_selection import train_test_split

# Divide the dataset into features and target variable
X = df.drop('Credit_Score', axis=1)
y = df['Credit_Score']

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [5]:
#une la base de datos X_train y y_train
train = pd.concat([X_train, y_train], axis=1)
# Muestra las primeras filas del dataframe
train.head()

,ID,Customer_ID,Month,Name,Age,SSN,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
75220,0x1cebe,CUS_0x475f,May,Tomz,20,782-04-7216,Journalist,101399.13,8535.927500,1,...,Good,1061.06,42.681159,24 Years and 9 Months,No,132.674897,114.2993860848862,High_spent_Medium_value_payments,856.6184673945337,Standard
48955,0x134d9,CUS_0x88e5,April,Poornima Guptav,25,680-32-0710,Accountant,112882.68,9684.890000,5,...,Good,722.9,40.090839,28 Years and 11 Months,No,353.616124,166.44641009831145,High_spent_Large_value_payments,688.4264658667721,Good
44966,0x11d78,CUS_0xb59c,July,Robertad,49,#F%$D@*&8,Scientist,28101.46,2173.463807,5,...,Standard,454.67,23.607892,26 Years and 9 Months,No,268.268012,NaN,Low_spent_Small_value_payments,242.92108023576716,Good
13568,0x6582,CUS_0x2543,January,Robertai,34,272-87-2927,Manager,22438.27,1856.855833,7,...,_,167.57,27.094189,NaN,No,58.436308,105.16564449441844,Low_spent_Large_value_payments,292.0836308808341,Standard
92727,0x23551,CUS_0x20dc,August,Pascaleb,28,285-71-9431,Media_Manager,20975.4,1943.950000,2,...,Good,731.4,26.205042,24 Years and 3 Months,NM,16.196792,67.15820105635807,High_spent_Medium_value_payments,361.0400067119549,Good

In [6]:
#exporta la base de datos a un archivo csv
train.to_csv('/Users/eugenio/Documents/Notebooks_ArtificialIntelligence/Datasets/credit_score_train.csv', index=False)

In [7]:
#exporta la base de datos X_test a un archivo csv
X_test.to_csv('/Users/eugenio/Documents/Notebooks_ArtificialIntelligence/Datasets/credit_score_test.csv', index=False)

In [ ]:
#exportar la base de datos y_test a un archivo csv
y_test.to_csv('/Users/eugenio/Documents/Notebooks_ArtificialIntelligence/Datasets/solutions.csv', index=False)

In [9]:
#convierte la base de datos y_test a un dataframe listo para una competencia de Kaggle. creando una columna llamada "Credit_Score" y una columna llamada "Id" que va de 0 a len(y_test)-1. La ID va primero
y_test = pd.DataFrame(y_test)
y_test.reset_index(drop=True, inplace=True)
y_test['Id'] = y_test.index
y_test = y_test[['Id', 'Credit_Score']]
#exportar la base de datos y_test a un archivo csv
y_test.to_csv('/Users/eugenio/Documents/Notebooks_ArtificialIntelligence/Datasets/solutions.csv', index=False)

In [10]:
# Agrega otra columna a la base de datos "solutions.csv" que tenga una columna "Usage" con 50% valores "Public" y 50% "Private"
y_test['Usage'] = np.where(y_test.index < len(y_test) / 2, 'Public', 'Private')
#exportar la base de datos y_test a un archivo csv
y_test.to_csv('/Users/eugenio/Documents/Notebooks_ArtificialIntelligence/Datasets/solutions3.csv', index=False)

In [3]:
# importa la base de datos solutions.csv
solutions = pd.read_csv('/Users/eugenio/Documents/Notebooks_ArtificialIntelligence/Datasets/solutions_real.csv')

In [4]:
solutions

          Id Credit_Score
0          0         Good
1          1         Poor
2          2         Good
3          3         Poor
4          4         Good
...      ...          ...
19995  19995     Standard
19996  19996     Standard
19997  19997         Poor
19998  19998     Standard
19999  19999     Standard

[20000 rows x 2 columns]

In [6]:
#Cambia todos los datos de la columna "Credit_Score" a "nan"
solutions['Credit_Score'] = np.nan
#exportar la base de datos solutions.csv a un archivo csv
solutions.to_csv('/Users/eugenio/Documents/Notebooks_ArtificialIntelligence/Datasets/solutions_nan.csv', index=False)