# **Database to Kaggle**
Run this script to transform a dataset for a Kaggle competition

## 1. Import the dataset into a pandas DataFrame `db`

In [1]:
import pandas as pd

# Read the dataset
df = pd.read_csv('/Users/eugenio/Documents/Notebooks_ArtificialIntelligence/Datasets/credit_score.csv')

# Show first few rows
df.head()

/var/folders/8j/f0xtldm91_1c2bpdr69fxgzw0000gn/T/ipykernel_13425/2105662226.py:4: DtypeWarning: Columns (26) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/Users/eugenio/Documents/Notebooks_ArtificialIntelligence/Datasets/credit_score.csv')

,ID,Customer_ID,Month,Name,Age,SSN,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
0,0x1602,CUS_0xd40,January,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,...,_,809.98,26.822620,22 Years and 1 Months,No,49.574949,80.41529543900253,High_spent_Small_value_payments,312.49408867943663,Good
1,0x1603,CUS_0xd40,February,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,NaN,3,...,Good,809.98,31.944960,NaN,No,49.574949,118.28022162236736,Low_spent_Large_value_payments,284.62916249607184,Good
2,0x1604,CUS_0xd40,March,Aaron Maashoh,-500,821-00-0265,Scientist,19114.12,NaN,3,...,Good,809.98,28.609352,22 Years and 3 Months,No,49.574949,81.699521264648,Low_spent_Medium_value_payments,331.2098628537912,Good
3,0x1605,CUS_0xd40,April,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,NaN,3,...,Good,809.98,31.377862,22 Years and 4 Months,No,49.574949,199.4580743910713,Low_spent_Small_value_payments,223.45130972736786,Good
4,0x1606,CUS_0xd40,May,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,...,Good,809.98,24.797347,22 Years and 5 Months,No,49.574949,41.420153086217326,High_spent_Medium_value_payments,341.48923103222177,Good

## 2. Isolate features (`X`) and target variable (`y`)

In [2]:
# Divide the dataset into features and target variable
X = df.drop('Credit_Score', axis=1)
y = df['Credit_Score']

## 3. Divide the dataset in training and testing sets

In [3]:
# Import the train_test_split function
from sklearn.model_selection import train_test_split

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

## 4. Save the `X_train`, `y_train`, and `X_test` dataframes to `.csv` files

In [4]:
# Save the training and testing sets to CSV files
X_train.to_csv("X_train_Kaggle.csv", index=False)
X_test.to_csv("X_test_Kaggle.csv", index=False)
y_train.to_csv("y_train_Kaggle.csv", index=False)

## 5. Create the `solutionsIDClassUsage` dataframe

In [5]:
# Create a dataframe with the following columns:
# "id" with values from 1 to the length of y_test
# "class" with the values of y_test
# "usage" with 50% of the values "Public" and 50% "Private" randomized
import numpy as np
# Create a new DataFrame with the specified columns
solutionsIdClassUsage = pd.DataFrame({
    "id": range(1, len(y_test) + 1),  # Generar IDs desde 1 hasta la longitud de y_test
    "class": y_test.values,  # Columna de clase con los valores de y_test
})
# Randomly assign "Public" and "Private" to the "usage" column
usage_values = np.random.choice(["Public", "Private"], size=len(solutionsIdClassUsage), p=[0.05, 0.95])
solutionsIdClassUsage["Usage"] = usage_values

In [6]:
# Display the first few rows of the new DataFrame
solutionsIdClassUsage.head(10)

   id     class    Usage
0   1      Good  Private
1   2      Poor  Private
2   3      Good  Private
3   4      Poor  Private
4   5      Good  Private
5   6      Poor  Private
6   7      Good  Private
7   8      Poor  Private
8   9      Good  Private
9  10  Standard  Private

In [7]:
# Export the DataFrame to a CSV file
solutionsIdClassUsage.to_csv("solutionsIdClassUsage.csv", index=False)

In [8]:
# Display the shape of the DataFrame
solutionsIdClassUsage.shape

(30000, 3)

## 6. Create the `sample_submission` dataframe

In [9]:
# Create the sample_submission file with "id" and "class" columns. The length of "id" is the same as that of y_test, and the "class" column should have all values ​​equal to 0.
sample_submission = pd.DataFrame({
    "id": range(1, len(y_test) + 1),  # Generate IDs from 1 to the length of y_test
    "class": 0  # Column of class with all values equal to 0
})
# Show the first few rows of the sample_submission DataFrame
sample_submission.head()

   id  class
0   1      0
1   2      0
2   3      0
3   4      0
4   5      0

In [10]:
# Display the shape of the DataFrame
sample_submission.shape

(30000, 2)

In [12]:
# Save the sample_submission DataFrame to a CSV file
sample_submission.to_csv("sample_submission_credit.csv", index=False)